### PR TITLE
add styles

### PR DESCRIPTION
**Pull request by alisonjoseph**
Add styles

### CODE REVIEW

**Comment by matt-kruse** [comment]
I like it! The only thing I don't prefer is that the loading indicator doesn't show any progress. I load 8 gyms for a local leaderboard, and it takes a while. I like to see some form of progress to indicate that things are actually loading.

**Comment by matt-kruse** [comment]
Lost the alternate row striping in the last commit?

**Comment by alisonjoseph** [comment]
I agree on the loader.. not sure how to easily add one in that shows progress though?

**Comment by alisonjoseph** [comment]
fixed the background color, changed it to white and accidentally threw it on the `*` so it applied everywhere

**Comment by alisonjoseph** [comment]
Ohh, just noticed your original loader does show progress. I'll remove mine for now then

**Comment by matt-kruse** [comment]
If you want to include a placeholder for a percentage of loading, I can calculate that and populate it in js. I like the new loader!

**Comment by alisonjoseph** [comment]
Added back in w/ the % in the middle of the loader

**Pull request merged**
